service: marketplace-auth-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_CLIENT_SECRET: ${env:AUTH0_CLIENT_SECRET}

plugins:
  - serverless-plugin-monorepo

functions:
  login:
    handler: ./dist/handlers/login.handler
    events:
      - httpApi:
          method: POST 
          path: /login
  authorizer:
    handler: ./dist/handlers/authorizer.handler

  package: 
    exclude: 
      - src/**/*.ts 
      - node_modules/.bin/** 
      - '*.json'
