createOrderQueuePolicy:
  Type: 'AWS::SQS::QueuePolicy'
  Properties:
    Queues:
      - !Ref createOrdersQueue
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: 'Allow'
          Principal:
            Service: 'events.amazonaws.com'
          Action: 'sqs:SendMessage'
          Resource: !GetAtt createOrdersQueue.Arn
