service: marketplace-orders-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: true
    authorizers:
      authenticationRequired:
        type: request
        functionArn: !ImportValue ${self:custom.authorizerFunction.exportName}
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:PutItem
      Resource:
        - ${self:custom.ordersTable.arn}
  environment:
    ORDERS_TABLE_NAME: ${self:custom.ordersTable.name}

functions:
  createOrder:
    handler: ./dist/handlers/createOrder.handler
    events:
      - sqs:
          arn: !GetAtt createOrdersQueue.Arn

resources:
  Resources:
    ordersEventBus: ${file('./resources/eventbridge/ordersEventBus.yml'):ordersEventBus}
    ordersTable: ${file('./resources/dynamodb/ordersTable.yml'):ordersTable}
    createOrderRule: ${file('./resources/eventbridge/createOrderRule.yml'):createOrderRule}
    createOrdersQueue: ${file('./resources/sqs/createOrdersQueue.yml'):createOrdersQueue}
    createOrderQueuePolicy: ${file('./resources/sqs/createOrderQueuePolicy.yml'):createOrderQueuePolicy}
  Outputs:
    OrdersEventBusArn:
      Value: !GetAtt ordersEventBus.Arn
      Export:
          Name: "orders-event-bus-arn"

plugins:
  - serverless-plugin-monorepo

package: 
    exclude: 
      - src/**/*.ts 
      - node_modules/.bin/** 
      - '*.json'

custom:
  authorizerFunction:
    exportName: authorizerArn

  ordersTable:
    name: ${env:ORDERS_TABLE_NAME}
    arn: !GetAtt ordersTable.Arn

  ordersEventBus:
    name: "orders-event-bus"
