service: marketplace-orders-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  authorizer: 

  httpApi:
    cors: true
    authorizers:
      requireAuthentication:
        type: request
        functionArn: !ImportValue ${self:custom.authorizerFunction.exportName}
     
functions:
  test1:
    handler: ./dist/handlers/test1.handler
    events:
      - eventBridge:
          eventBus: !Ref ordersEventBus
          pattern:
            detail:
              type:
                - CREATE_ORDER
resources:
  Resources:
    ordersEventBus: 
        Type: AWS::Events::EventBus
        Properties: 
            Name: "orders-event-bus"
  Outputs:
    OrdersEventBusArn:
      Value: !GetAtt ordersEventBus.Arn
      Export:
          Name: "orders-event-bus-arn"

plugins:
  - serverless-plugin-monorepo

package: 
    exclude: 
      - src/**/*.ts 
      - node_modules/.bin/** 
      - '*.json'

custom:
  authorizerFunction:
    exportName:
      Fn::Join:
        - "-"
        - - 'sls-marketplace-auth-service'
          - ${opt:stage, 'dev'}
          - 'AuthorizerLambdaFunctionQualifiedArn'

