productsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.productsTable.name} 
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      - AttributeName: "creationDate"
        AttributeType: N
      - AttributeName: "inStock"
        AttributeType: S
    KeySchema:
      - AttributeName: id 
        KeyType: HASH
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    GlobalSecondaryIndexes:
      - IndexName: "inStockCreationDateGsi"
        KeySchema:
          - AttributeName: "inStock"
            KeyType: "HASH"
          - AttributeName: "creationDate"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: "userIdGsi"
        KeySchema:
          -
            AttributeName: "userId"
            KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
