service: marketplace-products-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    PRODUCTS_TABLE_NAME: ${self:custom.productsTable.name}
  iamRoleStatements:
    - Effect: Allow
      Action: 
      - dynamodb:Query
      Resource: 
        - Fn::Join:
          - ""
          - - ${self:custom.productsTable.arn}
            - "/*"

    - Effect: Allow
      Action:
      - dynamodb:PutItem
      Resource:
        - ${self:custom.productsTable.arn}
  authorizer: 

  httpApi:
    cors: true
    authorizers:
      requireAuthentication:
        type: request
        functionArn: !ImportValue ${self:custom.authorizerFunction.exportName}
     
plugins:
  - serverless-plugin-monorepo

functions:
  addProduct:
    handler: ./dist/handlers/addProduct.handler
    events:
      - httpApi:
          method: POST
          path: /products
          authorizer:
            name: requireAuthentication
  getProducts:
    handler: ./dist/handlers/getProducts.handler
    events:
      - httpApi:
          method: GET 
          path: /products
          authorizer:
            name: requireAuthentication
  getMyProducts:
    handler: ./dist/handlers/getMyProducts.handler
    events:
      - httpApi:
          method: GET 
          path: /products/me
          authorizer:
            name: requireAuthentication

resources:
  Resources:
    productsTable: ${file('./resources/dynamodb/productsTable.yml'):productsTable}
    
package: 
    exclude: 
      - src/**/*.ts 
      - node_modules/.bin/** 
      - '*.json'

custom:
  productsTable:
    name: ${env:PRODUCTS_TABLE_NAME}
    arn: !GetAtt productsTable.Arn
  authorizerFunction:
    exportName:
      Fn::Join:
        - "-"
        - - 'sls-marketplace-auth-service'
          - ${opt:stage, 'dev'}
          - 'AuthorizerLambdaFunctionQualifiedArn'

