service: marketplace-products-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    PRODUCTS_TABLE_NAME: ${self:custom.productsTable.name}
    PRODUCT_IMAGES_BUCKET_NAME: ${env:PRODUCT_IMAGES_BUCKET_NAME}
    ORDERS_EVENT_BUS_ARN: !ImportValue orders-event-bus-arn
  iamRoleStatements:
    - Effect: Allow
      Action: 
      - dynamodb:Query
      Resource: 
        - Fn::Join:
          - ""
          - - ${self:custom.productsTable.arn}
            - "/*"
        - ${self:custom.productsTable.arn}

    - Effect: Allow
      Action:
      - dynamodb:PutItem
      Resource:
        - ${self:custom.productsTable.arn}

    - Effect: Allow
      Action:
      - 's3:*'
      Resource:
        - !GetAtt productImagesBucket.Arn
        - Fn::Join:
          - ""
          - - !GetAtt productImagesBucket.Arn
            - "/*"

    - Effect: Allow
      Action:
      - 'events:PutEvents'
      Resource:
        - !ImportValue orders-event-bus-arn

  authorizer: 

  httpApi:
    cors: true
    authorizers:
      authenticationRequired:
        type: request
        functionArn: !ImportValue ${self:custom.authorizerFunction.exportName}
     
plugins:
  - serverless-plugin-monorepo

functions:
  addProduct:
    handler: ./dist/handlers/addProduct.handler
    events:
      - httpApi:
          method: POST
          path: /products
          authorizer:
            name: authenticationRequired
  getProducts:
    handler: ./dist/handlers/getProducts.handler
    events:
      - httpApi:
          method: GET 
          path: /products
          authorizer:
            name: authenticationRequired
  getMyProducts:
    handler: ./dist/handlers/getMyProducts.handler
    events:
      - httpApi:
          method: GET 
          path: /products/me
          authorizer:
            name: authenticationRequired
  buyProduct:
    handler: ./dist/handlers/buyProduct.handler
    events:
      - httpApi:
          method: POST
          path: /products/{id}/buy
          authorizer:
            name: authenticationRequired

resources:
  Resources:
    productsTable: ${file('./resources/dynamodb/productsTable.yml'):productsTable}
    productImagesBucket: ${file('./resources/s3/productImagesBucket.yml'):productImagesBucket}

package: 
    exclude: 
      - src/**/*.ts 
      - node_modules/.bin/** 
      - '*.json'

custom:
  productsTable:
    name: ${env:PRODUCTS_TABLE_NAME}
    arn: !GetAtt productsTable.Arn
  authorizerFunction:
    exportName:
      Fn::Join:
        - "-"
        - - 'sls-marketplace-auth-service'
          - ${opt:stage, 'dev'}
          - 'AuthorizerLambdaFunctionQualifiedArn'

